name: federated_plugin_web
description: Web implementation of federated_plugin to retrieve current battery level.
version: 0.0.1
homepage:
publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  federated_plugin_platform_interface:
    path: ../federated_plugin_platform_interface

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  pedantic: ^1.11.0
  mockito: ^5.0.2

flutter:
  plugin:
    platforms:
      web:
        pluginClass: FederatedPlugin
        fileName: federated_plugin_web.dart
