name: desktop_photo_search
description: Search for Photos, using the Unsplash API.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ^2.11.0
  flutter: ^2.0.0

dependencies:
  flutter:
    sdk: flutter
  built_collection: ^5.0.0
  built_value: ^8.0.3
  cupertino_icons: ^1.0.2
  file_selector: ^0.8.2
  file_selector_linux: ^0.0.1
  file_selector_macos: ^0.0.1
  file_selector_windows: ^0.0.1
  http: ^0.13.0
  logging: ^0.11.3+2
  flutter_simple_treeview: ^2.0.1
  menubar:
    git:
      url: https://github.com/google/flutter-desktop-embedding.git
      path: plugins/menubar
  meta: ^1.1.8
  pedantic: ^1.9.0
  provider: ^5.0.0
  transparent_image: ^2.0.0
  uuid: ^3.0.1
  url_launcher: ^6.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  async: ^2.4.0
  build: ^1.2.2
  build_runner: ^1.10.4
  built_value_generator: ^8.0.3
  grinder: ^0.8.3
  msix: ^0.1.5
  source_gen: ^0.9.4
  test: ^1.9.4

flutter:
  uses-material-design: true

msix_config:
  display_name: Flutter Desktop Photo Search
  publisher_display_name: flutter.dev
  publisher: CN=01A6D5C0-D51A-4EEE-8DD0-F134DDD378F7
  identity_name: 16354flutter.dev.FlutterDesktopPhotoSearch
  msix_version: 1.0.0.0
  icons_background_color: "#ffffff"
  architecture: x64
  # See https://docs.microsoft.com/en-us/windows/uwp/packaging/app-capability-declarations
  capabilities: "internetClient"
