name: jsonexample
description: A demonstration of JSON parsing

environment:
  sdk: '>=2.12.0-0 <3.0.0'

dependencies:
  json_annotation: ^4.0.0-0
  built_collection: ^5.0.0-0
  built_value: ^8.0.0-0

  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.11.1
  built_value_generator: ^8.0.0-0
  json_serializable: ^4.0.0-0
  pedantic: ^1.9.0

flutter:
  uses-material-design: true
