name: tool
publish_to: none

environment:                                                            
  sdk: '>=2.10.0 <3.0.0'

dependencies:
  markdown: ^4.0.0-nullsafety.0
  path: ^1.8.0-nullsafety.3
