name: testing_app
description: A sample that shows testing in Flutter.

version: 1.0.0+1

environment:
  sdk: ">=2.10.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.0
  provider: ^4.1.3

dev_dependencies:
  integration_test: ^1.0.1
  flutter_test:
    sdk: flutter
  test: ^1.14.4
  pedantic: ^1.9.0

flutter:
  uses-material-design: true
